language: java
jdk:
- oraclejdk8
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag v1.0.${TRAVIS_BUILD_NUMBER}
  - git push -q https://$GITHUB_KEY@github.com/NyaaCat/buc --follow-tags
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_KEY
  file:
  - build/libs/buc-1.0.${TRAVIS_BUILD_NUMBER}.jar
  on:
    tags: false
    all_branches: true
  skip_cleanup: true
branches:
  only:
    - master